[theme]
primaryColor = "#b0231d"          # Azul do seu logo #f0f2f6
backgroundColor = "#ffffff"       # Fundo branco
secondaryBackgroundColor = "#f0f2f6" # Cinza claro para o menu lateral
textColor = "#31333F"
font = "sans serif"
