[theme]
primaryColor = "#004a87"          # Azul do seu logo
backgroundColor = "#ffffff"       # Fundo branco
secondaryBackgroundColor = "#f0f2f6" # Cinza claro para o menu lateral
textColor = "#31333F"
font = "sans serif"
